/* soapH.h
   Generated by gSOAP 2.8.96 for face.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void * SOAP_FMAC4 soap_getelement(struct soap*, const char*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void * SOAP_FMAC4 soap_dupelement(struct soap*, const void*, int);
SOAP_FMAC3 void SOAP_FMAC4 soap_delelement(const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);
SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap *soap, struct soap_clist*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fbase(int, int);
SOAP_FMAC3 void SOAP_FMAC4 soap_finsert(struct soap*, int, int, void*, size_t, const void*, void**);

#ifndef SOAP_TYPE_byte_DEFINED
#define SOAP_TYPE_byte_DEFINED

inline void soap_default_byte(struct soap *soap, char *a)
{
	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_byte
	*a = SOAP_DEFAULT_byte;
#else
	*a = (char)0;
#endif
}
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 char * SOAP_FMAC4 soap_new_byte(struct soap *soap, int n = -1);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

inline int soap_write_byte(struct soap *soap, char const*p)
{
	soap_free_temp(soap);
	if (p)
	{	if (soap_begin_send(soap) || ::soap_put_byte(soap, p, "byte", "") || soap_end_send(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_PUT_byte(struct soap *soap, const char *URL, char const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_byte(soap, p, "byte", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_byte(struct soap *soap, const char *URL, char const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_byte(soap, p, "byte", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_byte(struct soap *soap, const char *URL, char const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_byte(soap, p, "byte", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

inline int soap_read_byte(struct soap *soap, char *p)
{
	if (p)
	{	if (soap_begin_recv(soap) || ::soap_get_byte(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_byte(struct soap *soap, const char *URL, char *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_byte(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_byte(struct soap *soap, char *p)
{
	if (::soap_read_byte(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE_int_DEFINED
#define SOAP_TYPE_int_DEFINED

inline void soap_default_int(struct soap *soap, int *a)
{
	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_int
	*a = SOAP_DEFAULT_int;
#else
	*a = (int)0;
#endif
}
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int * SOAP_FMAC4 soap_new_int(struct soap *soap, int n = -1);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

inline int soap_write_int(struct soap *soap, int const*p)
{
	soap_free_temp(soap);
	if (p)
	{	if (soap_begin_send(soap) || ::soap_put_int(soap, p, "int", "") || soap_end_send(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_PUT_int(struct soap *soap, const char *URL, int const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_int(soap, p, "int", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_int(struct soap *soap, const char *URL, int const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_int(soap, p, "int", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_int(struct soap *soap, const char *URL, int const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_int(soap, p, "int", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

inline int soap_read_int(struct soap *soap, int *p)
{
	if (p)
	{	if (soap_begin_recv(soap) || ::soap_get_int(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_int(struct soap *soap, const char *URL, int *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_int(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_int(struct soap *soap, int *p)
{
	if (::soap_read_int(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE_float_DEFINED
#define SOAP_TYPE_float_DEFINED

inline void soap_default_float(struct soap *soap, float *a)
{
	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_float
	*a = SOAP_DEFAULT_float;
#else
	*a = (float)0;
#endif
}
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

SOAP_FMAC3 float * SOAP_FMAC4 soap_new_float(struct soap *soap, int n = -1);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);

inline int soap_write_float(struct soap *soap, float const*p)
{
	soap_free_temp(soap);
	if (p)
	{	if (soap_begin_send(soap) || ::soap_put_float(soap, p, "float", "") || soap_end_send(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_PUT_float(struct soap *soap, const char *URL, float const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_float(soap, p, "float", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_float(struct soap *soap, const char *URL, float const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_float(soap, p, "float", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_float(struct soap *soap, const char *URL, float const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_float(soap, p, "float", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);

inline int soap_read_float(struct soap *soap, float *p)
{
	if (p)
	{	if (soap_begin_recv(soap) || ::soap_get_float(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_float(struct soap *soap, const char *URL, float *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_float(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_float(struct soap *soap, float *p)
{
	if (::soap_read_float(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE_std__string_DEFINED
#define SOAP_TYPE_std__string_DEFINED

inline void soap_default_std__string(struct soap *soap, std::string *p)
{
	(void)soap; /* appease -Wall -Werror */
	p->erase();
}
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);

#define soap_std__string2s(soap, a) ((a).c_str())
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);

#define soap_s2std__string(soap, s, a) soap_s2stdchar((soap), (s), (a), 1, 0, -1, NULL)
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);
SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1)
{
	return soap_instantiate_std__string(soap, n, NULL, NULL, NULL);
}

inline std::string * soap_new_req_std__string(
	struct soap *soap)
{
	std::string *_p = ::soap_new_std__string(soap);
	if (_p)
	{	::soap_default_std__string(soap, _p);
	}
	return _p;
}

inline std::string * soap_new_set_std__string(
	struct soap *soap)
{
	std::string *_p = ::soap_new_std__string(soap);
	if (_p)
	{	::soap_default_std__string(soap, _p);
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

inline int soap_write_std__string(struct soap *soap, std::string const*p)
{
	soap_free_temp(soap);
	if (p)
	{	if (soap_begin_send(soap) || ::soap_put_std__string(soap, p, "string", "") || soap_end_send(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_PUT_std__string(struct soap *soap, const char *URL, std::string const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_std__string(soap, p, "string", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_std__string(struct soap *soap, const char *URL, std::string const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_std__string(soap, p, "string", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_std__string(struct soap *soap, const char *URL, std::string const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_std__string(soap, p, "string", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

inline int soap_read_std__string(struct soap *soap, std::string *p)
{
	if (p)
	{	if (soap_begin_recv(soap) || ::soap_get_std__string(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_std__string(struct soap *soap, const char *URL, std::string *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_std__string(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_std__string(struct soap *soap, std::string *p)
{
	if (::soap_read_std__string(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault_DEFINED
#define SOAP_TYPE_SOAP_ENV__Fault_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1)
{
	return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL);
}

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(
	struct soap *soap)
{
	struct SOAP_ENV__Fault *_p = ::soap_new_SOAP_ENV__Fault(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Fault(soap, _p);
	}
	return _p;
}

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(
	struct soap *soap,
	char *faultcode,
	char *faultstring,
	char *faultactor,
	struct SOAP_ENV__Detail *detail,
	struct SOAP_ENV__Code *SOAP_ENV__Code,
	struct SOAP_ENV__Reason *SOAP_ENV__Reason,
	char *SOAP_ENV__Node,
	char *SOAP_ENV__Role,
	struct SOAP_ENV__Detail *SOAP_ENV__Detail)
{
	struct SOAP_ENV__Fault *_p = ::soap_new_SOAP_ENV__Fault(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Fault(soap, _p);
		_p->faultcode = faultcode;
		_p->faultstring = faultstring;
		_p->faultactor = faultactor;
		_p->detail = detail;
		_p->SOAP_ENV__Code = SOAP_ENV__Code;
		_p->SOAP_ENV__Reason = SOAP_ENV__Reason;
		_p->SOAP_ENV__Node = SOAP_ENV__Node;
		_p->SOAP_ENV__Role = SOAP_ENV__Role;
		_p->SOAP_ENV__Detail = SOAP_ENV__Detail;
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

inline int soap_write_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Fault(soap, p), 0) || ::soap_put_SOAP_ENV__Fault(soap, p, "SOAP-ENV:Fault", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_SOAP_ENV__Fault(struct soap *soap, const char *URL, struct SOAP_ENV__Fault const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Fault(soap, p), 0) || ::soap_put_SOAP_ENV__Fault(soap, p, "SOAP-ENV:Fault", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_SOAP_ENV__Fault(struct soap *soap, const char *URL, struct SOAP_ENV__Fault const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Fault(soap, p), 0) || ::soap_put_SOAP_ENV__Fault(soap, p, "SOAP-ENV:Fault", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_SOAP_ENV__Fault(struct soap *soap, const char *URL, struct SOAP_ENV__Fault const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Fault(soap, p), 0) || ::soap_put_SOAP_ENV__Fault(soap, p, "SOAP-ENV:Fault", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

inline int soap_read_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p)
{
	if (p)
	{	::soap_default_SOAP_ENV__Fault(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Fault(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_SOAP_ENV__Fault(struct soap *soap, const char *URL, struct SOAP_ENV__Fault *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Fault(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p)
{
	if (::soap_read_SOAP_ENV__Fault(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_SOAP_ENV__Reason_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1)
{
	return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL);
}

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(
	struct soap *soap)
{
	struct SOAP_ENV__Reason *_p = ::soap_new_SOAP_ENV__Reason(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Reason(soap, _p);
	}
	return _p;
}

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(
	struct soap *soap,
	char *SOAP_ENV__Text)
{
	struct SOAP_ENV__Reason *_p = ::soap_new_SOAP_ENV__Reason(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Reason(soap, _p);
		_p->SOAP_ENV__Text = SOAP_ENV__Text;
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

inline int soap_write_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Reason(soap, p), 0) || ::soap_put_SOAP_ENV__Reason(soap, p, "SOAP-ENV:Reason", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_SOAP_ENV__Reason(struct soap *soap, const char *URL, struct SOAP_ENV__Reason const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Reason(soap, p), 0) || ::soap_put_SOAP_ENV__Reason(soap, p, "SOAP-ENV:Reason", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_SOAP_ENV__Reason(struct soap *soap, const char *URL, struct SOAP_ENV__Reason const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Reason(soap, p), 0) || ::soap_put_SOAP_ENV__Reason(soap, p, "SOAP-ENV:Reason", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_SOAP_ENV__Reason(struct soap *soap, const char *URL, struct SOAP_ENV__Reason const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Reason(soap, p), 0) || ::soap_put_SOAP_ENV__Reason(soap, p, "SOAP-ENV:Reason", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

inline int soap_read_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p)
{
	if (p)
	{	::soap_default_SOAP_ENV__Reason(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Reason(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_SOAP_ENV__Reason(struct soap *soap, const char *URL, struct SOAP_ENV__Reason *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Reason(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p)
{
	if (::soap_read_SOAP_ENV__Reason(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_SOAP_ENV__Detail_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1)
{
	return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL);
}

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(
	struct soap *soap,
	int __type,
	void *fault)
{
	struct SOAP_ENV__Detail *_p = ::soap_new_SOAP_ENV__Detail(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Detail(soap, _p);
		_p->__type = __type;
		_p->fault = fault;
	}
	return _p;
}

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(
	struct soap *soap,
	char *__any,
	int __type,
	void *fault)
{
	struct SOAP_ENV__Detail *_p = ::soap_new_SOAP_ENV__Detail(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Detail(soap, _p);
		_p->__any = __any;
		_p->__type = __type;
		_p->fault = fault;
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

inline int soap_write_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Detail(soap, p), 0) || ::soap_put_SOAP_ENV__Detail(soap, p, "SOAP-ENV:Detail", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_SOAP_ENV__Detail(struct soap *soap, const char *URL, struct SOAP_ENV__Detail const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Detail(soap, p), 0) || ::soap_put_SOAP_ENV__Detail(soap, p, "SOAP-ENV:Detail", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_SOAP_ENV__Detail(struct soap *soap, const char *URL, struct SOAP_ENV__Detail const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Detail(soap, p), 0) || ::soap_put_SOAP_ENV__Detail(soap, p, "SOAP-ENV:Detail", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_SOAP_ENV__Detail(struct soap *soap, const char *URL, struct SOAP_ENV__Detail const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Detail(soap, p), 0) || ::soap_put_SOAP_ENV__Detail(soap, p, "SOAP-ENV:Detail", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

inline int soap_read_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p)
{
	if (p)
	{	::soap_default_SOAP_ENV__Detail(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Detail(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_SOAP_ENV__Detail(struct soap *soap, const char *URL, struct SOAP_ENV__Detail *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Detail(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p)
{
	if (::soap_read_SOAP_ENV__Detail(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code_DEFINED
#define SOAP_TYPE_SOAP_ENV__Code_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1)
{
	return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL);
}

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(
	struct soap *soap)
{
	struct SOAP_ENV__Code *_p = ::soap_new_SOAP_ENV__Code(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Code(soap, _p);
	}
	return _p;
}

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(
	struct soap *soap,
	char *SOAP_ENV__Value,
	struct SOAP_ENV__Code *SOAP_ENV__Subcode)
{
	struct SOAP_ENV__Code *_p = ::soap_new_SOAP_ENV__Code(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Code(soap, _p);
		_p->SOAP_ENV__Value = SOAP_ENV__Value;
		_p->SOAP_ENV__Subcode = SOAP_ENV__Subcode;
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

inline int soap_write_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Code(soap, p), 0) || ::soap_put_SOAP_ENV__Code(soap, p, "SOAP-ENV:Code", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_SOAP_ENV__Code(struct soap *soap, const char *URL, struct SOAP_ENV__Code const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Code(soap, p), 0) || ::soap_put_SOAP_ENV__Code(soap, p, "SOAP-ENV:Code", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_SOAP_ENV__Code(struct soap *soap, const char *URL, struct SOAP_ENV__Code const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Code(soap, p), 0) || ::soap_put_SOAP_ENV__Code(soap, p, "SOAP-ENV:Code", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_SOAP_ENV__Code(struct soap *soap, const char *URL, struct SOAP_ENV__Code const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Code(soap, p), 0) || ::soap_put_SOAP_ENV__Code(soap, p, "SOAP-ENV:Code", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

inline int soap_read_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p)
{
	if (p)
	{	::soap_default_SOAP_ENV__Code(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Code(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_SOAP_ENV__Code(struct soap *soap, const char *URL, struct SOAP_ENV__Code *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Code(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p)
{
	if (::soap_read_SOAP_ENV__Code(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header_DEFINED
#define SOAP_TYPE_SOAP_ENV__Header_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1)
{
	return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL);
}

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(
	struct soap *soap)
{
	struct SOAP_ENV__Header *_p = ::soap_new_SOAP_ENV__Header(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Header(soap, _p);
	}
	return _p;
}

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(
	struct soap *soap)
{
	struct SOAP_ENV__Header *_p = ::soap_new_SOAP_ENV__Header(soap);
	if (_p)
	{	::soap_default_SOAP_ENV__Header(soap, _p);
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

inline int soap_write_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_SOAP_ENV__Header(soap, p), 0) || ::soap_put_SOAP_ENV__Header(soap, p, "SOAP-ENV:Header", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_SOAP_ENV__Header(struct soap *soap, const char *URL, struct SOAP_ENV__Header const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Header(soap, p), 0) || ::soap_put_SOAP_ENV__Header(soap, p, "SOAP-ENV:Header", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_SOAP_ENV__Header(struct soap *soap, const char *URL, struct SOAP_ENV__Header const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Header(soap, p), 0) || ::soap_put_SOAP_ENV__Header(soap, p, "SOAP-ENV:Header", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_SOAP_ENV__Header(struct soap *soap, const char *URL, struct SOAP_ENV__Header const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_SOAP_ENV__Header(soap, p), 0) || ::soap_put_SOAP_ENV__Header(soap, p, "SOAP-ENV:Header", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

inline int soap_read_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p)
{
	if (p)
	{	::soap_default_SOAP_ENV__Header(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_SOAP_ENV__Header(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_SOAP_ENV__Header(struct soap *soap, const char *URL, struct SOAP_ENV__Header *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_SOAP_ENV__Header(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p)
{
	if (::soap_read_SOAP_ENV__Header(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#endif

#ifndef SOAP_TYPE_ns__FaceDetectByBase64_DEFINED
#define SOAP_TYPE_ns__FaceDetectByBase64_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__FaceDetectByBase64(struct soap*, struct ns__FaceDetectByBase64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__FaceDetectByBase64(struct soap*, const struct ns__FaceDetectByBase64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__FaceDetectByBase64(struct soap*, const char*, int, const struct ns__FaceDetectByBase64 *, const char*);
SOAP_FMAC3 struct ns__FaceDetectByBase64 * SOAP_FMAC4 soap_in_ns__FaceDetectByBase64(struct soap*, const char*, struct ns__FaceDetectByBase64 *, const char*);
SOAP_FMAC1 struct ns__FaceDetectByBase64 * SOAP_FMAC2 soap_instantiate_ns__FaceDetectByBase64(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__FaceDetectByBase64 * soap_new_ns__FaceDetectByBase64(struct soap *soap, int n = -1)
{
	return soap_instantiate_ns__FaceDetectByBase64(soap, n, NULL, NULL, NULL);
}

inline struct ns__FaceDetectByBase64 * soap_new_req_ns__FaceDetectByBase64(
	struct soap *soap,
	const std::string& img_base64)
{
	struct ns__FaceDetectByBase64 *_p = ::soap_new_ns__FaceDetectByBase64(soap);
	if (_p)
	{	::soap_default_ns__FaceDetectByBase64(soap, _p);
		_p->img_base64 = img_base64;
	}
	return _p;
}

inline struct ns__FaceDetectByBase64 * soap_new_set_ns__FaceDetectByBase64(
	struct soap *soap,
	const std::string& img_base64)
{
	struct ns__FaceDetectByBase64 *_p = ::soap_new_ns__FaceDetectByBase64(soap);
	if (_p)
	{	::soap_default_ns__FaceDetectByBase64(soap, _p);
		_p->img_base64 = img_base64;
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__FaceDetectByBase64(struct soap*, const struct ns__FaceDetectByBase64 *, const char*, const char*);

inline int soap_write_ns__FaceDetectByBase64(struct soap *soap, struct ns__FaceDetectByBase64 const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_ns__FaceDetectByBase64(soap, p), 0) || ::soap_put_ns__FaceDetectByBase64(soap, p, "ns:FaceDetectByBase64", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_ns__FaceDetectByBase64(struct soap *soap, const char *URL, struct ns__FaceDetectByBase64 const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByBase64(soap, p), 0) || ::soap_put_ns__FaceDetectByBase64(soap, p, "ns:FaceDetectByBase64", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_ns__FaceDetectByBase64(struct soap *soap, const char *URL, struct ns__FaceDetectByBase64 const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByBase64(soap, p), 0) || ::soap_put_ns__FaceDetectByBase64(soap, p, "ns:FaceDetectByBase64", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_ns__FaceDetectByBase64(struct soap *soap, const char *URL, struct ns__FaceDetectByBase64 const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByBase64(soap, p), 0) || ::soap_put_ns__FaceDetectByBase64(soap, p, "ns:FaceDetectByBase64", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct ns__FaceDetectByBase64 * SOAP_FMAC4 soap_get_ns__FaceDetectByBase64(struct soap*, struct ns__FaceDetectByBase64 *, const char*, const char*);

inline int soap_read_ns__FaceDetectByBase64(struct soap *soap, struct ns__FaceDetectByBase64 *p)
{
	if (p)
	{	::soap_default_ns__FaceDetectByBase64(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_ns__FaceDetectByBase64(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_ns__FaceDetectByBase64(struct soap *soap, const char *URL, struct ns__FaceDetectByBase64 *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_ns__FaceDetectByBase64(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_ns__FaceDetectByBase64(struct soap *soap, struct ns__FaceDetectByBase64 *p)
{
	if (::soap_read_ns__FaceDetectByBase64(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE_ns__FaceDetectByBase64Response_DEFINED
#define SOAP_TYPE_ns__FaceDetectByBase64Response_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__FaceDetectByBase64Response(struct soap*, struct ns__FaceDetectByBase64Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__FaceDetectByBase64Response(struct soap*, const struct ns__FaceDetectByBase64Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__FaceDetectByBase64Response(struct soap*, const char*, int, const struct ns__FaceDetectByBase64Response *, const char*);
SOAP_FMAC3 struct ns__FaceDetectByBase64Response * SOAP_FMAC4 soap_in_ns__FaceDetectByBase64Response(struct soap*, const char*, struct ns__FaceDetectByBase64Response *, const char*);
SOAP_FMAC1 struct ns__FaceDetectByBase64Response * SOAP_FMAC2 soap_instantiate_ns__FaceDetectByBase64Response(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__FaceDetectByBase64Response * soap_new_ns__FaceDetectByBase64Response(struct soap *soap, int n = -1)
{
	return soap_instantiate_ns__FaceDetectByBase64Response(soap, n, NULL, NULL, NULL);
}

inline struct ns__FaceDetectByBase64Response * soap_new_req_ns__FaceDetectByBase64Response(
	struct soap *soap)
{
	struct ns__FaceDetectByBase64Response *_p = ::soap_new_ns__FaceDetectByBase64Response(soap);
	if (_p)
	{	::soap_default_ns__FaceDetectByBase64Response(soap, _p);
	}
	return _p;
}

inline struct ns__FaceDetectByBase64Response * soap_new_set_ns__FaceDetectByBase64Response(
	struct soap *soap,
	struct FaceRes *face_res)
{
	struct ns__FaceDetectByBase64Response *_p = ::soap_new_ns__FaceDetectByBase64Response(soap);
	if (_p)
	{	::soap_default_ns__FaceDetectByBase64Response(soap, _p);
		_p->face_res = face_res;
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__FaceDetectByBase64Response(struct soap*, const struct ns__FaceDetectByBase64Response *, const char*, const char*);

inline int soap_write_ns__FaceDetectByBase64Response(struct soap *soap, struct ns__FaceDetectByBase64Response const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_ns__FaceDetectByBase64Response(soap, p), 0) || ::soap_put_ns__FaceDetectByBase64Response(soap, p, "ns:FaceDetectByBase64Response", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_ns__FaceDetectByBase64Response(struct soap *soap, const char *URL, struct ns__FaceDetectByBase64Response const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByBase64Response(soap, p), 0) || ::soap_put_ns__FaceDetectByBase64Response(soap, p, "ns:FaceDetectByBase64Response", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_ns__FaceDetectByBase64Response(struct soap *soap, const char *URL, struct ns__FaceDetectByBase64Response const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByBase64Response(soap, p), 0) || ::soap_put_ns__FaceDetectByBase64Response(soap, p, "ns:FaceDetectByBase64Response", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_ns__FaceDetectByBase64Response(struct soap *soap, const char *URL, struct ns__FaceDetectByBase64Response const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByBase64Response(soap, p), 0) || ::soap_put_ns__FaceDetectByBase64Response(soap, p, "ns:FaceDetectByBase64Response", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct ns__FaceDetectByBase64Response * SOAP_FMAC4 soap_get_ns__FaceDetectByBase64Response(struct soap*, struct ns__FaceDetectByBase64Response *, const char*, const char*);

inline int soap_read_ns__FaceDetectByBase64Response(struct soap *soap, struct ns__FaceDetectByBase64Response *p)
{
	if (p)
	{	::soap_default_ns__FaceDetectByBase64Response(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_ns__FaceDetectByBase64Response(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_ns__FaceDetectByBase64Response(struct soap *soap, const char *URL, struct ns__FaceDetectByBase64Response *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_ns__FaceDetectByBase64Response(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_ns__FaceDetectByBase64Response(struct soap *soap, struct ns__FaceDetectByBase64Response *p)
{
	if (::soap_read_ns__FaceDetectByBase64Response(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE_ns__FaceDetectByImgpath_DEFINED
#define SOAP_TYPE_ns__FaceDetectByImgpath_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__FaceDetectByImgpath(struct soap*, struct ns__FaceDetectByImgpath *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__FaceDetectByImgpath(struct soap*, const struct ns__FaceDetectByImgpath *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__FaceDetectByImgpath(struct soap*, const char*, int, const struct ns__FaceDetectByImgpath *, const char*);
SOAP_FMAC3 struct ns__FaceDetectByImgpath * SOAP_FMAC4 soap_in_ns__FaceDetectByImgpath(struct soap*, const char*, struct ns__FaceDetectByImgpath *, const char*);
SOAP_FMAC1 struct ns__FaceDetectByImgpath * SOAP_FMAC2 soap_instantiate_ns__FaceDetectByImgpath(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__FaceDetectByImgpath * soap_new_ns__FaceDetectByImgpath(struct soap *soap, int n = -1)
{
	return soap_instantiate_ns__FaceDetectByImgpath(soap, n, NULL, NULL, NULL);
}

inline struct ns__FaceDetectByImgpath * soap_new_req_ns__FaceDetectByImgpath(
	struct soap *soap,
	const std::string& img_path)
{
	struct ns__FaceDetectByImgpath *_p = ::soap_new_ns__FaceDetectByImgpath(soap);
	if (_p)
	{	::soap_default_ns__FaceDetectByImgpath(soap, _p);
		_p->img_path = img_path;
	}
	return _p;
}

inline struct ns__FaceDetectByImgpath * soap_new_set_ns__FaceDetectByImgpath(
	struct soap *soap,
	const std::string& img_path)
{
	struct ns__FaceDetectByImgpath *_p = ::soap_new_ns__FaceDetectByImgpath(soap);
	if (_p)
	{	::soap_default_ns__FaceDetectByImgpath(soap, _p);
		_p->img_path = img_path;
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__FaceDetectByImgpath(struct soap*, const struct ns__FaceDetectByImgpath *, const char*, const char*);

inline int soap_write_ns__FaceDetectByImgpath(struct soap *soap, struct ns__FaceDetectByImgpath const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_ns__FaceDetectByImgpath(soap, p), 0) || ::soap_put_ns__FaceDetectByImgpath(soap, p, "ns:FaceDetectByImgpath", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_ns__FaceDetectByImgpath(struct soap *soap, const char *URL, struct ns__FaceDetectByImgpath const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByImgpath(soap, p), 0) || ::soap_put_ns__FaceDetectByImgpath(soap, p, "ns:FaceDetectByImgpath", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_ns__FaceDetectByImgpath(struct soap *soap, const char *URL, struct ns__FaceDetectByImgpath const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByImgpath(soap, p), 0) || ::soap_put_ns__FaceDetectByImgpath(soap, p, "ns:FaceDetectByImgpath", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_ns__FaceDetectByImgpath(struct soap *soap, const char *URL, struct ns__FaceDetectByImgpath const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByImgpath(soap, p), 0) || ::soap_put_ns__FaceDetectByImgpath(soap, p, "ns:FaceDetectByImgpath", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct ns__FaceDetectByImgpath * SOAP_FMAC4 soap_get_ns__FaceDetectByImgpath(struct soap*, struct ns__FaceDetectByImgpath *, const char*, const char*);

inline int soap_read_ns__FaceDetectByImgpath(struct soap *soap, struct ns__FaceDetectByImgpath *p)
{
	if (p)
	{	::soap_default_ns__FaceDetectByImgpath(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_ns__FaceDetectByImgpath(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_ns__FaceDetectByImgpath(struct soap *soap, const char *URL, struct ns__FaceDetectByImgpath *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_ns__FaceDetectByImgpath(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_ns__FaceDetectByImgpath(struct soap *soap, struct ns__FaceDetectByImgpath *p)
{
	if (::soap_read_ns__FaceDetectByImgpath(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE_ns__FaceDetectByImgpathResponse_DEFINED
#define SOAP_TYPE_ns__FaceDetectByImgpathResponse_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__FaceDetectByImgpathResponse(struct soap*, struct ns__FaceDetectByImgpathResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__FaceDetectByImgpathResponse(struct soap*, const struct ns__FaceDetectByImgpathResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__FaceDetectByImgpathResponse(struct soap*, const char*, int, const struct ns__FaceDetectByImgpathResponse *, const char*);
SOAP_FMAC3 struct ns__FaceDetectByImgpathResponse * SOAP_FMAC4 soap_in_ns__FaceDetectByImgpathResponse(struct soap*, const char*, struct ns__FaceDetectByImgpathResponse *, const char*);
SOAP_FMAC1 struct ns__FaceDetectByImgpathResponse * SOAP_FMAC2 soap_instantiate_ns__FaceDetectByImgpathResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__FaceDetectByImgpathResponse * soap_new_ns__FaceDetectByImgpathResponse(struct soap *soap, int n = -1)
{
	return soap_instantiate_ns__FaceDetectByImgpathResponse(soap, n, NULL, NULL, NULL);
}

inline struct ns__FaceDetectByImgpathResponse * soap_new_req_ns__FaceDetectByImgpathResponse(
	struct soap *soap)
{
	struct ns__FaceDetectByImgpathResponse *_p = ::soap_new_ns__FaceDetectByImgpathResponse(soap);
	if (_p)
	{	::soap_default_ns__FaceDetectByImgpathResponse(soap, _p);
	}
	return _p;
}

inline struct ns__FaceDetectByImgpathResponse * soap_new_set_ns__FaceDetectByImgpathResponse(
	struct soap *soap,
	struct FaceRes *face_res)
{
	struct ns__FaceDetectByImgpathResponse *_p = ::soap_new_ns__FaceDetectByImgpathResponse(soap);
	if (_p)
	{	::soap_default_ns__FaceDetectByImgpathResponse(soap, _p);
		_p->face_res = face_res;
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__FaceDetectByImgpathResponse(struct soap*, const struct ns__FaceDetectByImgpathResponse *, const char*, const char*);

inline int soap_write_ns__FaceDetectByImgpathResponse(struct soap *soap, struct ns__FaceDetectByImgpathResponse const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_ns__FaceDetectByImgpathResponse(soap, p), 0) || ::soap_put_ns__FaceDetectByImgpathResponse(soap, p, "ns:FaceDetectByImgpathResponse", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_ns__FaceDetectByImgpathResponse(struct soap *soap, const char *URL, struct ns__FaceDetectByImgpathResponse const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByImgpathResponse(soap, p), 0) || ::soap_put_ns__FaceDetectByImgpathResponse(soap, p, "ns:FaceDetectByImgpathResponse", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_ns__FaceDetectByImgpathResponse(struct soap *soap, const char *URL, struct ns__FaceDetectByImgpathResponse const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByImgpathResponse(soap, p), 0) || ::soap_put_ns__FaceDetectByImgpathResponse(soap, p, "ns:FaceDetectByImgpathResponse", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_ns__FaceDetectByImgpathResponse(struct soap *soap, const char *URL, struct ns__FaceDetectByImgpathResponse const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__FaceDetectByImgpathResponse(soap, p), 0) || ::soap_put_ns__FaceDetectByImgpathResponse(soap, p, "ns:FaceDetectByImgpathResponse", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct ns__FaceDetectByImgpathResponse * SOAP_FMAC4 soap_get_ns__FaceDetectByImgpathResponse(struct soap*, struct ns__FaceDetectByImgpathResponse *, const char*, const char*);

inline int soap_read_ns__FaceDetectByImgpathResponse(struct soap *soap, struct ns__FaceDetectByImgpathResponse *p)
{
	if (p)
	{	::soap_default_ns__FaceDetectByImgpathResponse(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_ns__FaceDetectByImgpathResponse(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_ns__FaceDetectByImgpathResponse(struct soap *soap, const char *URL, struct ns__FaceDetectByImgpathResponse *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_ns__FaceDetectByImgpathResponse(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_ns__FaceDetectByImgpathResponse(struct soap *soap, struct ns__FaceDetectByImgpathResponse *p)
{
	if (::soap_read_ns__FaceDetectByImgpathResponse(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE_FaceRes_DEFINED
#define SOAP_TYPE_FaceRes_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_FaceRes(struct soap*, struct FaceRes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_FaceRes(struct soap*, const struct FaceRes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_FaceRes(struct soap*, const char*, int, const struct FaceRes *, const char*);
SOAP_FMAC3 struct FaceRes * SOAP_FMAC4 soap_in_FaceRes(struct soap*, const char*, struct FaceRes *, const char*);
SOAP_FMAC1 struct FaceRes * SOAP_FMAC2 soap_instantiate_FaceRes(struct soap*, int, const char*, const char*, size_t*);

inline struct FaceRes * soap_new_FaceRes(struct soap *soap, int n = -1)
{
	return soap_instantiate_FaceRes(soap, n, NULL, NULL, NULL);
}

inline struct FaceRes * soap_new_req_FaceRes(
	struct soap *soap,
	int __size,
	struct ns__SingleFaceInfo **__ptr)
{
	struct FaceRes *_p = ::soap_new_FaceRes(soap);
	if (_p)
	{	::soap_default_FaceRes(soap, _p);
		_p->__size = __size;
		_p->__ptr = __ptr;
	}
	return _p;
}

inline struct FaceRes * soap_new_set_FaceRes(
	struct soap *soap,
	int __size,
	struct ns__SingleFaceInfo **__ptr)
{
	struct FaceRes *_p = ::soap_new_FaceRes(soap);
	if (_p)
	{	::soap_default_FaceRes(soap, _p);
		_p->__size = __size;
		_p->__ptr = __ptr;
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_FaceRes(struct soap*, const struct FaceRes *, const char*, const char*);

inline int soap_write_FaceRes(struct soap *soap, struct FaceRes const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_FaceRes(soap, p), 0) || ::soap_put_FaceRes(soap, p, "FaceRes", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_FaceRes(struct soap *soap, const char *URL, struct FaceRes const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_FaceRes(soap, p), 0) || ::soap_put_FaceRes(soap, p, "FaceRes", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_FaceRes(struct soap *soap, const char *URL, struct FaceRes const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_FaceRes(soap, p), 0) || ::soap_put_FaceRes(soap, p, "FaceRes", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_FaceRes(struct soap *soap, const char *URL, struct FaceRes const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_FaceRes(soap, p), 0) || ::soap_put_FaceRes(soap, p, "FaceRes", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct FaceRes * SOAP_FMAC4 soap_get_FaceRes(struct soap*, struct FaceRes *, const char*, const char*);

inline int soap_read_FaceRes(struct soap *soap, struct FaceRes *p)
{
	if (p)
	{	::soap_default_FaceRes(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_FaceRes(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_FaceRes(struct soap *soap, const char *URL, struct FaceRes *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_FaceRes(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_FaceRes(struct soap *soap, struct FaceRes *p)
{
	if (::soap_read_FaceRes(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE_ns__SingleFaceInfo_DEFINED
#define SOAP_TYPE_ns__SingleFaceInfo_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__SingleFaceInfo(struct soap*, struct ns__SingleFaceInfo *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__SingleFaceInfo(struct soap*, const struct ns__SingleFaceInfo *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__SingleFaceInfo(struct soap*, const char*, int, const struct ns__SingleFaceInfo *, const char*);
SOAP_FMAC3 struct ns__SingleFaceInfo * SOAP_FMAC4 soap_in_ns__SingleFaceInfo(struct soap*, const char*, struct ns__SingleFaceInfo *, const char*);
SOAP_FMAC1 struct ns__SingleFaceInfo * SOAP_FMAC2 soap_instantiate_ns__SingleFaceInfo(struct soap*, int, const char*, const char*, size_t*);

inline struct ns__SingleFaceInfo * soap_new_ns__SingleFaceInfo(struct soap *soap, int n = -1)
{
	return soap_instantiate_ns__SingleFaceInfo(soap, n, NULL, NULL, NULL);
}

inline struct ns__SingleFaceInfo * soap_new_req_ns__SingleFaceInfo(
	struct soap *soap,
	float x1,
	float y1,
	float x2,
	float y2,
	float score,
	float landmarks[10])
{
	struct ns__SingleFaceInfo *_p = ::soap_new_ns__SingleFaceInfo(soap);
	if (_p)
	{	::soap_default_ns__SingleFaceInfo(soap, _p);
		_p->x1 = x1;
		_p->y1 = y1;
		_p->x2 = x2;
		_p->y2 = y2;
		_p->score = score;
		for (int i = 0; i < 10; i++)
			_p->landmarks[i] = landmarks[i];
	}
	return _p;
}

inline struct ns__SingleFaceInfo * soap_new_set_ns__SingleFaceInfo(
	struct soap *soap,
	float x1,
	float y1,
	float x2,
	float y2,
	float score,
	float landmarks[10])
{
	struct ns__SingleFaceInfo *_p = ::soap_new_ns__SingleFaceInfo(soap);
	if (_p)
	{	::soap_default_ns__SingleFaceInfo(soap, _p);
		_p->x1 = x1;
		_p->y1 = y1;
		_p->x2 = x2;
		_p->y2 = y2;
		_p->score = score;
		for (int i = 0; i < 10; i++)
			_p->landmarks[i] = landmarks[i];
	}
	return _p;
}
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__SingleFaceInfo(struct soap*, const struct ns__SingleFaceInfo *, const char*, const char*);

inline int soap_write_ns__SingleFaceInfo(struct soap *soap, struct ns__SingleFaceInfo const*p)
{
	soap_free_temp(soap);
	if (soap_begin_send(soap) || (::soap_serialize_ns__SingleFaceInfo(soap, p), 0) || ::soap_put_ns__SingleFaceInfo(soap, p, "ns:SingleFaceInfo", "") || soap_end_send(soap))
			return soap->error;
	return SOAP_OK;
}

inline int soap_PUT_ns__SingleFaceInfo(struct soap *soap, const char *URL, struct ns__SingleFaceInfo const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__SingleFaceInfo(soap, p), 0) || ::soap_put_ns__SingleFaceInfo(soap, p, "ns:SingleFaceInfo", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_ns__SingleFaceInfo(struct soap *soap, const char *URL, struct ns__SingleFaceInfo const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__SingleFaceInfo(soap, p), 0) || ::soap_put_ns__SingleFaceInfo(soap, p, "ns:SingleFaceInfo", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_ns__SingleFaceInfo(struct soap *soap, const char *URL, struct ns__SingleFaceInfo const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || (::soap_serialize_ns__SingleFaceInfo(soap, p), 0) || ::soap_put_ns__SingleFaceInfo(soap, p, "ns:SingleFaceInfo", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 struct ns__SingleFaceInfo * SOAP_FMAC4 soap_get_ns__SingleFaceInfo(struct soap*, struct ns__SingleFaceInfo *, const char*, const char*);

inline int soap_read_ns__SingleFaceInfo(struct soap *soap, struct ns__SingleFaceInfo *p)
{
	if (p)
	{	::soap_default_ns__SingleFaceInfo(soap, p);
		if (soap_begin_recv(soap) || ::soap_get_ns__SingleFaceInfo(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_ns__SingleFaceInfo(struct soap *soap, const char *URL, struct ns__SingleFaceInfo *p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_ns__SingleFaceInfo(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_ns__SingleFaceInfo(struct soap *soap, struct ns__SingleFaceInfo *p)
{
	if (::soap_read_ns__SingleFaceInfo(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Reason_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Detail_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
#endif

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
#define SOAP_TYPE_PointerToSOAP_ENV__Code_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
#endif

#endif

#ifndef SOAP_TYPE_PointerToFaceRes_DEFINED
#define SOAP_TYPE_PointerToFaceRes_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToFaceRes(struct soap*, struct FaceRes *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToFaceRes(struct soap*, const char *, int, struct FaceRes *const*, const char *);
SOAP_FMAC3 struct FaceRes ** SOAP_FMAC4 soap_in_PointerToFaceRes(struct soap*, const char*, struct FaceRes **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToFaceRes(struct soap*, struct FaceRes *const*, const char*, const char*);
SOAP_FMAC3 struct FaceRes ** SOAP_FMAC4 soap_get_PointerToFaceRes(struct soap*, struct FaceRes **, const char*, const char*);
#endif

#ifndef SOAP_TYPE_PointerToPointerTons__SingleFaceInfo_DEFINED
#define SOAP_TYPE_PointerToPointerTons__SingleFaceInfo_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons__SingleFaceInfo(struct soap*, struct ns__SingleFaceInfo **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons__SingleFaceInfo(struct soap*, const char *, int, struct ns__SingleFaceInfo **const*, const char *);
SOAP_FMAC3 struct ns__SingleFaceInfo *** SOAP_FMAC4 soap_in_PointerToPointerTons__SingleFaceInfo(struct soap*, const char*, struct ns__SingleFaceInfo ***, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons__SingleFaceInfo(struct soap*, struct ns__SingleFaceInfo **const*, const char*, const char*);
SOAP_FMAC3 struct ns__SingleFaceInfo *** SOAP_FMAC4 soap_get_PointerToPointerTons__SingleFaceInfo(struct soap*, struct ns__SingleFaceInfo ***, const char*, const char*);
#endif

#ifndef SOAP_TYPE_PointerTons__SingleFaceInfo_DEFINED
#define SOAP_TYPE_PointerTons__SingleFaceInfo_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__SingleFaceInfo(struct soap*, struct ns__SingleFaceInfo *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__SingleFaceInfo(struct soap*, const char *, int, struct ns__SingleFaceInfo *const*, const char *);
SOAP_FMAC3 struct ns__SingleFaceInfo ** SOAP_FMAC4 soap_in_PointerTons__SingleFaceInfo(struct soap*, const char*, struct ns__SingleFaceInfo **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__SingleFaceInfo(struct soap*, struct ns__SingleFaceInfo *const*, const char*, const char*);
SOAP_FMAC3 struct ns__SingleFaceInfo ** SOAP_FMAC4 soap_get_PointerTons__SingleFaceInfo(struct soap*, struct ns__SingleFaceInfo **, const char*, const char*);
#endif

#ifndef SOAP_TYPE__QName_DEFINED
#define SOAP_TYPE__QName_DEFINED

inline void soap_default__QName(struct soap *soap, char **a)
{
	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT__QName
	*a = SOAP_DEFAULT__QName;
#else
	*a = (char *)0;
#endif
}
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);

#define soap__QName2s(soap, a) soap_QName2s(soap, (a))
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);

#define soap_s2_QName(soap, s, a) soap_s2QName((soap), (s), (char**)(a), 0, -1, NULL)
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_instantiate__QName soap_instantiate_string


#define soap_new__QName soap_new_string

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

inline int soap_write__QName(struct soap *soap, char *const*p)
{
	soap_free_temp(soap);
	if (p)
	{	if (soap_begin_send(soap) || ::soap_put__QName(soap, p, "QName", "") || soap_end_send(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_PUT__QName(struct soap *soap, const char *URL, char *const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put__QName(soap, p, "QName", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH__QName(struct soap *soap, const char *URL, char *const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put__QName(soap, p, "QName", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send__QName(struct soap *soap, const char *URL, char *const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put__QName(soap, p, "QName", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

inline int soap_read__QName(struct soap *soap, char **p)
{
	if (p)
	{	if (soap_begin_recv(soap) || ::soap_get__QName(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET__QName(struct soap *soap, const char *URL, char **p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read__QName(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv__QName(struct soap *soap, char **p)
{
	if (::soap_read__QName(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE__XML_DEFINED
#define SOAP_TYPE__XML_DEFINED
#endif

#ifndef SOAP_TYPE_string_DEFINED
#define SOAP_TYPE_string_DEFINED

inline void soap_default_string(struct soap *soap, char **a)
{
	(void)soap; /* appease -Wall -Werror */
#ifdef SOAP_DEFAULT_string
	*a = SOAP_DEFAULT_string;
#else
	*a = (char *)0;
#endif
}
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);

#define soap_string2s(soap, a) (a)
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);

#define soap_s2string(soap, s, a) soap_s2char((soap), (s), (char**)(a), 1, 0, -1, NULL)
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

SOAP_FMAC3 char * * SOAP_FMAC4 soap_new_string(struct soap *soap, int n = -1);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

inline int soap_write_string(struct soap *soap, char *const*p)
{
	soap_free_temp(soap);
	if (p)
	{	if (soap_begin_send(soap) || ::soap_put_string(soap, p, "string", "") || soap_end_send(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_PUT_string(struct soap *soap, const char *URL, char *const*p)
{
	soap_free_temp(soap);
	if (soap_PUT(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_string(soap, p, "string", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_PATCH_string(struct soap *soap, const char *URL, char *const*p)
{
	soap_free_temp(soap);
	if (soap_PATCH(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_string(soap, p, "string", "") || soap_end_send(soap) || soap_recv_empty_response(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}

inline int soap_POST_send_string(struct soap *soap, const char *URL, char *const*p)
{
	soap_free_temp(soap);
	if (soap_POST(soap, URL, NULL, "text/xml; charset=utf-8") || ::soap_put_string(soap, p, "string", "") || soap_end_send(soap))
		return soap_closesock(soap);
	return SOAP_OK;
}
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

inline int soap_read_string(struct soap *soap, char **p)
{
	if (p)
	{	if (soap_begin_recv(soap) || ::soap_get_string(soap, p, NULL, NULL) == NULL || soap_end_recv(soap))
			return soap->error;
	}
	return SOAP_OK;
}

inline int soap_GET_string(struct soap *soap, const char *URL, char **p)
{
	if (soap_GET(soap, URL, NULL) || ::soap_read_string(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}

inline int soap_POST_recv_string(struct soap *soap, char **p)
{
	if (::soap_read_string(soap, p))
		return soap_closesock(soap);
	return soap_closesock(soap);
}
#endif

#ifndef SOAP_TYPE_Array10Offloat_DEFINED
#define SOAP_TYPE_Array10Offloat_DEFINED
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Array10Offloat(struct soap*, float [10]);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Array10Offloat(struct soap*, float const[10]);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Array10Offloat(struct soap*, const char*, int, float const[10], const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_Array10Offloat(struct soap*, const char*, float [10], const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Array10Offloat(struct soap*, float const[10], const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_Array10Offloat(struct soap*, float [10], const char*, const char*);
#endif

#endif

/* End of soapH.h */
