/* soapfaceProxy.h
   Generated by gSOAP 2.8.96 for face.h

gSOAP XML Web services tools
Copyright (C) 2000-2018, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapfaceProxy_H
#define soapfaceProxy_H
#include "soapH.h"

    class SOAP_CMAC faceProxy {
      public:
        /// Context to manage proxy IO and data
        struct soap *soap;
        /// flag indicating that this context is owned by this proxy and should be deleted by the destructor
        bool soap_own;
        /// Endpoint URL of service 'faceProxy' (change as needed)
        const char *soap_endpoint;
        /// Variables globally declared in face.h, if any
        /// Construct a proxy with new managing context
        faceProxy();
        /// Copy constructor
        faceProxy(const faceProxy& rhs);
        /// Construct proxy given a shared managing context
        faceProxy(struct soap*);
        /// Construct proxy given a shared managing context and endpoint URL
        faceProxy(struct soap*, const char *soap_endpoint_url);
        /// Constructor taking an endpoint URL
        faceProxy(const char *soap_endpoint_url);
        /// Constructor taking input and output mode flags for the new managing context
        faceProxy(soap_mode iomode);
        /// Constructor taking endpoint URL and input and output mode flags for the new managing context
        faceProxy(const char *soap_endpoint_url, soap_mode iomode);
        /// Constructor taking input and output mode flags for the new managing context
        faceProxy(soap_mode imode, soap_mode omode);
        /// Destructor deletes deserialized data and its managing context, when the context was allocated by the constructor
        virtual ~faceProxy();
        /// Initializer used by constructors
        virtual void faceProxy_init(soap_mode imode, soap_mode omode);
        /// Return a copy that has a new managing context with the same engine state
        virtual faceProxy *copy();
        /// Copy assignment
        faceProxy& operator=(const faceProxy&);
        /// Delete all deserialized data (uses soap_destroy() and soap_end())
        virtual void destroy();
        /// Delete all deserialized data and reset to default
        virtual void reset();
        /// Disables and removes SOAP Header from message by setting soap->header = NULL
        virtual void soap_noheader();
        /// Get SOAP Header structure (i.e. soap->header, which is NULL when absent)
        virtual ::SOAP_ENV__Header *soap_header();
        /// Get SOAP Fault structure (i.e. soap->fault, which is NULL when absent)
        virtual ::SOAP_ENV__Fault *soap_fault();
        /// Get SOAP Fault subcode QName string (NULL when absent)
        virtual const char *soap_fault_subcode();
        /// Get SOAP Fault string/reason (NULL when absent)
        virtual const char *soap_fault_string();
        /// Get SOAP Fault detail XML string (NULL when absent)
        virtual const char *soap_fault_detail();
        /// Close connection (normally automatic, except for send_X ops)
        virtual int soap_close_socket();
        /// Force close connection (can kill a thread blocked on IO)
        virtual int soap_force_close_socket();
        /// Print fault
        virtual void soap_print_fault(FILE*);
    #ifndef WITH_LEAN
    #ifndef WITH_COMPAT
        /// Print fault to stream
        virtual void soap_stream_fault(std::ostream&);
    #endif
        /// Write fault to buffer
        virtual char *soap_sprint_fault(char *buf, size_t len);
    #endif
        //
        /// Web service synchronous operation 'FaceDetectByImgpath' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FaceDetectByImgpath(const std::string& img_path, struct FaceRes *face_res) { return this->FaceDetectByImgpath(NULL, NULL, img_path, face_res); }
        /// Web service synchronous operation 'FaceDetectByImgpath' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FaceDetectByImgpath(const char *soap_endpoint_url, const char *soap_action, const std::string& img_path, struct FaceRes *face_res) { return this->send_FaceDetectByImgpath(soap_endpoint_url, soap_action, img_path) || this->recv_FaceDetectByImgpath(face_res) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FaceDetectByImgpath' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FaceDetectByImgpath(const char *soap_endpoint_url, const char *soap_action, const std::string& img_path);
        /// Web service asynchronous operation 'recv_FaceDetectByImgpath' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FaceDetectByImgpath(struct FaceRes *face_res);
        //
        /// Web service synchronous operation 'FaceDetectByBase64' with default endpoint and default SOAP Action header, returns SOAP_OK or error code
        virtual int FaceDetectByBase64(const std::string& img_base64, struct FaceRes *face_res) { return this->FaceDetectByBase64(NULL, NULL, img_base64, face_res); }
        /// Web service synchronous operation 'FaceDetectByBase64' to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int FaceDetectByBase64(const char *soap_endpoint_url, const char *soap_action, const std::string& img_base64, struct FaceRes *face_res) { return this->send_FaceDetectByBase64(soap_endpoint_url, soap_action, img_base64) || this->recv_FaceDetectByBase64(face_res) ? this->soap->error : SOAP_OK; }
        /// Web service asynchronous operation 'send_FaceDetectByBase64' to send a request message to the specified endpoint and SOAP Action header, returns SOAP_OK or error code
        virtual int send_FaceDetectByBase64(const char *soap_endpoint_url, const char *soap_action, const std::string& img_base64);
        /// Web service asynchronous operation 'recv_FaceDetectByBase64' to receive a response message from the connected endpoint, returns SOAP_OK or error code
        virtual int recv_FaceDetectByBase64(struct FaceRes *face_res);
    };
#endif
